import { vi } from "vitest";
import type { Platform } from "../platform/types";

export function createMockPlatform(overrides: Partial<Platform> = {}): Platform {
  return {
    createWindow: vi.fn(),
    closeWindow: vi.fn(),
    minimizeWindow: vi.fn(),
    maximizeWindow: vi.fn(),
    unmaximizeWindow: vi.fn(),
    isWindowMaximized: vi.fn(() => false),
    focusWindow: vi.fn(),
    createTab: vi.fn(),
    closeTab: vi.fn(),
    navigateTab: vi.fn(),
    getTabUrl: vi.fn(() => undefined),
    getTabTitle: vi.fn(() => undefined),
    setTabBounds: vi.fn(),
    hideTab: vi.fn(),
    hideAllTabs: vi.fn(),
    onTabEvent: vi.fn(() => () => {}),
    goBack: vi.fn(),
    goForward: vi.fn(),
    reload: vi.fn(),
    canGoBack: vi.fn(() => false),
    canGoForward: vi.fn(() => false),
    setTabZoomLevel: vi.fn(),
    getTabZoomLevel: vi.fn(() => 0),
    registerShortcut: vi.fn(),
    unregisterShortcut: vi.fn(),
    hookWebContents: vi.fn(),
    focusShell: vi.fn(),
    initTooltipOverlay: vi.fn(),
    showTooltip: vi.fn(),
    hideTooltip: vi.fn(),
    initContextMenuOverlay: vi.fn(),
    showContextMenu: vi.fn(async () => -1),
    hideContextMenu: vi.fn(),
    insertCSS: vi.fn(async () => "css-key"),
    removeInsertedCSS: vi.fn(),
    openExternal: vi.fn(),
    openPath: vi.fn(),
    readClipboard: vi.fn(() => ""),
    writeClipboard: vi.fn(),
    ...overrides,
  } as Platform;
}
