// ── Command names ────────────────────────────────────────────────
export const WINDOW_MINIMIZE = "window:minimize";
export const WINDOW_MAXIMIZE_RESTORE = "window:maximize-restore";
export const WINDOW_CLOSE = "window:close";
export const WINDOW_COPY_ADDRESS = "window:copy-address";
export const WINDOW_GO_BACK = "window:go-back";
export const WINDOW_GO_FORWARD = "window:go-forward";
export const WINDOW_RELOAD = "window:reload";
// ── Event names ──────────────────────────────────────────────────
export const WINDOW_MAXIMIZED_CHANGED = "window:maximized-changed";
export const TAB_LOADING_CHANGED = "tab:loading-changed";
